//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2009.01.21 um 01:55:07 GMT+01:00 
//


package de.thorstenberger.taskmodel.complex.jaxb.impl;

public class PaintSubTaskDefTypeImpl
    extends de.thorstenberger.taskmodel.complex.jaxb.impl.SubTaskDefTypeImpl
    implements de.thorstenberger.taskmodel.complex.jaxb.PaintSubTaskDefType, java.io.Serializable, com.sun.xml.bind.JAXBObject, de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.UnmarshallableObject, de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.XMLSerializable, de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.ValidatableObject
{

    private final static long serialVersionUID = 1L;
    protected de.thorstenberger.taskmodel.complex.jaxb.PaintSubTaskDefType.ImagesType _Images;
    protected boolean has_ColorChangeable;
    protected boolean _ColorChangeable;
    protected boolean has_StrokewidthChangeable;
    protected boolean _StrokewidthChangeable;
    protected de.thorstenberger.taskmodel.complex.jaxb.PaintSubTaskDefType.TextualAnswerType _TextualAnswer;
    public final static java.lang.Class version = (de.thorstenberger.taskmodel.complex.jaxb.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (de.thorstenberger.taskmodel.complex.jaxb.PaintSubTaskDefType.class);
    }

    public de.thorstenberger.taskmodel.complex.jaxb.PaintSubTaskDefType.ImagesType getImages() {
        return _Images;
    }

    public void setImages(de.thorstenberger.taskmodel.complex.jaxb.PaintSubTaskDefType.ImagesType value) {
        _Images = value;
    }

    public boolean isSetImages() {
        return (_Images!= null);
    }

    public void unsetImages() {
        _Images = null;
    }

    public boolean isColorChangeable() {
        return _ColorChangeable;
    }

    public void setColorChangeable(boolean value) {
        _ColorChangeable = value;
        has_ColorChangeable = true;
    }

    public boolean isSetColorChangeable() {
        return has_ColorChangeable;
    }

    public void unsetColorChangeable() {
        has_ColorChangeable = false;
    }

    public boolean isStrokewidthChangeable() {
        return _StrokewidthChangeable;
    }

    public void setStrokewidthChangeable(boolean value) {
        _StrokewidthChangeable = value;
        has_StrokewidthChangeable = true;
    }

    public boolean isSetStrokewidthChangeable() {
        return has_StrokewidthChangeable;
    }

    public void unsetStrokewidthChangeable() {
        has_StrokewidthChangeable = false;
    }

    public de.thorstenberger.taskmodel.complex.jaxb.PaintSubTaskDefType.TextualAnswerType getTextualAnswer() {
        return _TextualAnswer;
    }

    public void setTextualAnswer(de.thorstenberger.taskmodel.complex.jaxb.PaintSubTaskDefType.TextualAnswerType value) {
        _TextualAnswer = value;
    }

    public boolean isSetTextualAnswer() {
        return (_TextualAnswer!= null);
    }

    public void unsetTextualAnswer() {
        _TextualAnswer = null;
    }

    public de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.UnmarshallingEventHandler createUnmarshaller(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.UnmarshallingContext context) {
        return new de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        super.serializeBody(context);
        if (_Images!= null) {
            context.startElement("http://complex.taskmodel.thorstenberger.de/complexTaskDef", "images");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Images), "Images");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Images), "Images");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Images), "Images");
            context.endElement();
        }
        if (_TextualAnswer!= null) {
            context.startElement("http://complex.taskmodel.thorstenberger.de/complexTaskDef", "textualAnswer");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _TextualAnswer), "TextualAnswer");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _TextualAnswer), "TextualAnswer");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _TextualAnswer), "TextualAnswer");
            context.endElement();
        }
        if (has_ColorChangeable) {
            context.startElement("http://complex.taskmodel.thorstenberger.de/complexTaskDef", "colorChangeable");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printBoolean(((boolean) _ColorChangeable)), "ColorChangeable");
            } catch (java.lang.Exception e) {
                de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (has_StrokewidthChangeable) {
            context.startElement("http://complex.taskmodel.thorstenberger.de/complexTaskDef", "strokewidthChangeable");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printBoolean(((boolean) _StrokewidthChangeable)), "StrokewidthChangeable");
            } catch (java.lang.Exception e) {
                de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
    }

    public void serializeAttributes(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        super.serializeAttributes(context);
    }

    public void serializeURIs(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        super.serializeURIs(context);
    }

    public java.lang.Class getPrimaryInterface() {
        return (de.thorstenberger.taskmodel.complex.jaxb.PaintSubTaskDefType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\'com.sun.msv.grammar.trex"
+".ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/gramma"
+"r/NameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001a"
+"ignoreUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003pp\u0000sq\u0000~\u0000"
+"\u0000ppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/re"
+"laxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv"
+"/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000#com.sun.msv.datatype.xsd.String"
+"Type\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.datatype.xsd."
+"BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.Con"
+"creteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeI"
+"mpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/String;L\u0000\btypeNam"
+"eq\u0000~\u0000\u001cL\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpacePr"
+"ocessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0006stringsr\u00005co"
+"m.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0000xp\u0001sr\u00000com.sun.msv.grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\t"
+"localNameq\u0000~\u0000\u001cL\u0000\fnamespaceURIq\u0000~\u0000\u001cxpq\u0000~\u0000 q\u0000~\u0000\u001fsr\u0000\u001dcom.sun.ms"
+"v.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 com.sun.msv.gramma"
+"r.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u0010xq\u0000~\u0000\u0003s"
+"r\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\u0014ppsr\u0000\"com.s"
+"un.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0019q\u0000~\u0000\u001ft\u0000\u0005QNames"
+"r\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\"q\u0000~\u0000%sq\u0000~\u0000&q\u0000~\u00001q\u0000~\u0000\u001fsr\u0000#com.sun.msv.grammar.Si"
+"mpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001cL\u0000\fnamespaceURIq\u0000~\u0000"
+"\u001cxr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)htt"
+"p://www.w3.org/2001/XMLSchema-instancesr\u00000com.sun.msv.gramma"
+"r.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000,\u0001q\u0000~\u0000;s"
+"q\u0000~\u00005t\u0000\u0007problemt\u00009http://complex.taskmodel.thorstenberger.de"
+"/complexTaskDefsq\u0000~\u0000(ppsq\u0000~\u0000\u000fq\u0000~\u0000-p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0017sq\u0000~\u0000(ppsq\u0000"
+"~\u0000*q\u0000~\u0000-pq\u0000~\u0000.q\u0000~\u00007q\u0000~\u0000;sq\u0000~\u00005t\u0000\u0004hintq\u0000~\u0000?q\u0000~\u0000;sq\u0000~\u0000(ppsq\u0000~\u0000"
+"\u000fq\u0000~\u0000-p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0017sq\u0000~\u0000(ppsq\u0000~\u0000*q\u0000~\u0000-pq\u0000~\u0000.q\u0000~\u00007q\u0000~\u0000;sq\u0000~"
+"\u00005t\u0000\u000ecorrectionHintq\u0000~\u0000?q\u0000~\u0000;sq\u0000~\u0000(ppsq\u0000~\u0000\u000fq\u0000~\u0000-p\u0000sq\u0000~\u0000\u0000ppsq"
+"\u0000~\u0000\u000fpp\u0000sq\u0000~\u0000(ppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~"
+"\u0000\u0003q\u0000~\u0000-psq\u0000~\u0000*q\u0000~\u0000-psr\u00002com.sun.msv.grammar.Expression$AnySt"
+"ringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000<q\u0000~\u0000Xsr\u0000 com.sun.msv.gra"
+"mmar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u00006q\u0000~\u0000;sq\u0000~\u00005t\u0000Gde.thorstenb"
+"erger.taskmodel.complex.jaxb.PaintSubTaskDefType.ImagesTypet"
+"\u0000+http://java.sun.com/jaxb/xjc/dummy-elementssq\u0000~\u0000(ppsq\u0000~\u0000*q"
+"\u0000~\u0000-pq\u0000~\u0000.q\u0000~\u00007q\u0000~\u0000;sq\u0000~\u00005t\u0000\u0006imagesq\u0000~\u0000?q\u0000~\u0000;sq\u0000~\u0000(ppsq\u0000~\u0000\u000fq"
+"\u0000~\u0000-p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u000fpp\u0000sq\u0000~\u0000(ppsq\u0000~\u0000Sq\u0000~\u0000-psq\u0000~\u0000*q\u0000~\u0000-pq\u0000~\u0000X"
+"q\u0000~\u0000Zq\u0000~\u0000;sq\u0000~\u00005t\u0000Nde.thorstenberger.taskmodel.complex.jaxb."
+"PaintSubTaskDefType.TextualAnswerTypeq\u0000~\u0000]sq\u0000~\u0000(ppsq\u0000~\u0000*q\u0000~\u0000"
+"-pq\u0000~\u0000.q\u0000~\u00007q\u0000~\u0000;sq\u0000~\u00005t\u0000\rtextualAnswerq\u0000~\u0000?q\u0000~\u0000;sq\u0000~\u0000(ppsq\u0000"
+"~\u0000\u000fq\u0000~\u0000-p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0014ppsr\u0000$com.sun.msv.datatype.xsd.Boole"
+"anType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0019q\u0000~\u0000\u001ft\u0000\u0007booleanq\u0000~\u00003q\u0000~\u0000%sq\u0000~\u0000&q\u0000~\u0000uq"
+"\u0000~\u0000\u001fsq\u0000~\u0000(ppsq\u0000~\u0000*q\u0000~\u0000-pq\u0000~\u0000.q\u0000~\u00007q\u0000~\u0000;sq\u0000~\u00005t\u0000\u000fcolorChangea"
+"bleq\u0000~\u0000?q\u0000~\u0000;sq\u0000~\u0000(ppsq\u0000~\u0000\u000fq\u0000~\u0000-p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000rsq\u0000~\u0000(ppsq\u0000~\u0000"
+"*q\u0000~\u0000-pq\u0000~\u0000.q\u0000~\u00007q\u0000~\u0000;sq\u0000~\u00005t\u0000\u0015strokewidthChangeableq\u0000~\u0000?q\u0000~"
+"\u0000;sq\u0000~\u0000(ppsq\u0000~\u0000*q\u0000~\u0000-pq\u0000~\u0000\u0017sq\u0000~\u00005t\u0000\u0002idt\u0000\u0000q\u0000~\u0000;sq\u0000~\u0000(ppsq\u0000~\u0000*"
+"q\u0000~\u0000-psq\u0000~\u0000\u0014ppsr\u0000)com.sun.msv.datatype.xsd.EnumerationFacet\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0006valuest\u0000\u000fLjava/util/Set;xr\u00009com.sun.msv.datatyp"
+"e.xsd.DataTypeWithValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun"
+".msv.datatype.xsd.DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixe"
+"dZ\u0000\u0012needValueCheckFlagL\u0000\bbaseTypet\u0000)Lcom/sun/msv/datatype/xs"
+"d/XSDatatypeImpl;L\u0000\fconcreteTypet\u0000\'Lcom/sun/msv/datatype/xsd"
+"/ConcreteType;L\u0000\tfacetNameq\u0000~\u0000\u001cxq\u0000~\u0000\u001bq\u0000~\u0000?pq\u0000~\u0000#\u0000\u0000q\u0000~\u0000\u001eq\u0000~\u0000\u001e"
+"t\u0000\u000benumerationsr\u0000\u0011java.util.HashSet\u00baD\u0085\u0095\u0096\u00b8\u00b74\u0003\u0000\u0000xpw\f\u0000\u0000\u0000\u0010?@\u0000\u0000\u0000\u0000"
+"\u0000\u0005t\u0000\u0002det\u0000\u0002est\u0000\u0002ent\u0000\u0002frt\u0000\u0002ruxq\u0000~\u0000%sq\u0000~\u0000&t\u0000\u000estring-derivedq\u0000~\u0000"
+"?sq\u0000~\u00005t\u0000\rinputLanguageq\u0000~\u0000\u0086q\u0000~\u0000;sq\u0000~\u0000(ppsq\u0000~\u0000*q\u0000~\u0000-pq\u0000~\u0000rsq"
+"\u0000~\u00005t\u0000\u0013interactiveFeedbackq\u0000~\u0000\u0086q\u0000~\u0000;sq\u0000~\u0000(ppsq\u0000~\u0000*q\u0000~\u0000-pq\u0000~\u0000"
+"rsq\u0000~\u00005t\u0000\u0005trashq\u0000~\u0000\u0086q\u0000~\u0000;sr\u0000\"com.sun.msv.grammar.ExpressionP"
+"ool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionP"
+"ool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$Clos"
+"edHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/su"
+"n/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000&\u0001pq\u0000~\u0000\nq\u0000~\u0000\u0013q\u0000~\u0000Bq\u0000~\u0000Iq\u0000~"
+"\u0000\u0087q\u0000~\u0000\rq\u0000~\u0000@q\u0000~\u0000Gq\u0000~\u0000oq\u0000~\u0000qq\u0000~\u0000\fq\u0000~\u0000}q\u0000~\u0000{q\u0000~\u0000)q\u0000~\u0000Cq\u0000~\u0000Jq\u0000~"
+"\u0000^q\u0000~\u0000kq\u0000~\u0000Nq\u0000~\u0000Pq\u0000~\u0000dq\u0000~\u0000bq\u0000~\u0000\u000bq\u0000~\u0000wq\u0000~\u0000~q\u0000~\u0000Uq\u0000~\u0000gq\u0000~\u0000\u0082q\u0000~"
+"\u0000\u00a1q\u0000~\u0000\tq\u0000~\u0000\u009dq\u0000~\u0000\u000eq\u0000~\u0000\bq\u0000~\u0000\u0006q\u0000~\u0000Rq\u0000~\u0000fq\u0000~\u0000\u0005q\u0000~\u0000\u0007x"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public static class ImagesTypeImpl implements de.thorstenberger.taskmodel.complex.jaxb.PaintSubTaskDefType.ImagesType, java.io.Serializable, com.sun.xml.bind.JAXBObject, de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.UnmarshallableObject, de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.XMLSerializable, de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.ValidatableObject
    {

        private final static long serialVersionUID = 1L;
        protected java.lang.String _ImmutableBackgroundImage;
        protected java.lang.String _CorrectionTemplateImage;
        protected java.lang.String _MutableTemplateImage;
        public final static java.lang.Class version = (de.thorstenberger.taskmodel.complex.jaxb.impl.JAXBVersion.class);
        private static com.sun.msv.grammar.Grammar schemaFragment;

        private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
            return (de.thorstenberger.taskmodel.complex.jaxb.PaintSubTaskDefType.ImagesType.class);
        }

        public java.lang.String getImmutableBackgroundImage() {
            return _ImmutableBackgroundImage;
        }

        public void setImmutableBackgroundImage(java.lang.String value) {
            _ImmutableBackgroundImage = value;
        }

        public boolean isSetImmutableBackgroundImage() {
            return (_ImmutableBackgroundImage!= null);
        }

        public void unsetImmutableBackgroundImage() {
            _ImmutableBackgroundImage = null;
        }

        public java.lang.String getCorrectionTemplateImage() {
            return _CorrectionTemplateImage;
        }

        public void setCorrectionTemplateImage(java.lang.String value) {
            _CorrectionTemplateImage = value;
        }

        public boolean isSetCorrectionTemplateImage() {
            return (_CorrectionTemplateImage!= null);
        }

        public void unsetCorrectionTemplateImage() {
            _CorrectionTemplateImage = null;
        }

        public java.lang.String getMutableTemplateImage() {
            return _MutableTemplateImage;
        }

        public void setMutableTemplateImage(java.lang.String value) {
            _MutableTemplateImage = value;
        }

        public boolean isSetMutableTemplateImage() {
            return (_MutableTemplateImage!= null);
        }

        public void unsetMutableTemplateImage() {
            _MutableTemplateImage = null;
        }

        public de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.UnmarshallingEventHandler createUnmarshaller(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.UnmarshallingContext context) {
            return new de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl.Unmarshaller(context);
        }

        public void serializeBody(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
            if (_MutableTemplateImage!= null) {
                context.startElement("http://complex.taskmodel.thorstenberger.de/complexTaskDef", "mutableTemplateImage");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _MutableTemplateImage), "MutableTemplateImage");
                } catch (java.lang.Exception e) {
                    de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
            if (_ImmutableBackgroundImage!= null) {
                context.startElement("http://complex.taskmodel.thorstenberger.de/complexTaskDef", "immutableBackgroundImage");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _ImmutableBackgroundImage), "ImmutableBackgroundImage");
                } catch (java.lang.Exception e) {
                    de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
            if (_CorrectionTemplateImage!= null) {
                context.startElement("http://complex.taskmodel.thorstenberger.de/complexTaskDef", "correctionTemplateImage");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _CorrectionTemplateImage), "CorrectionTemplateImage");
                } catch (java.lang.Exception e) {
                    de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
        }

        public void serializeAttributes(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
        }

        public void serializeURIs(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
        }

        public java.lang.Class getPrimaryInterface() {
            return (de.thorstenberger.taskmodel.complex.jaxb.PaintSubTaskDefType.ImagesType.class);
        }

        public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
            if (schemaFragment == null) {
                schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsr\u0000\u001dcom.sun.msv.grammar.ChoiceEx"
+"p\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000\'com.sun.msv.grammar.trex.ElementPatt"
+"ern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;"
+"xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndecl"
+"aredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003sr\u0000\u0011java.lang.Boolea"
+"n\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000p\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun.msv.grammar.Dat"
+"aExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exc"
+"eptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000#c"
+"om.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysVali"
+"dxr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr"
+"\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.su"
+"n.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit"
+"\u0000\u0012Ljava/lang/String;L\u0000\btypeNameq\u0000~\u0000\u0018L\u0000\nwhiteSpacet\u0000.Lcom/sun"
+"/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org"
+"/2001/XMLSchemat\u0000\u0006stringsr\u00005com.sun.msv.datatype.xsd.WhiteSp"
+"aceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd"
+".WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Ex"
+"pression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv"
+".util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0018L\u0000\fnamespaceURIq"
+"\u0000~\u0000\u0018xpq\u0000~\u0000\u001cq\u0000~\u0000\u001bsq\u0000~\u0000\u0007ppsr\u0000 com.sun.msv.grammar.AttributeExp"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\nxq\u0000~\u0000\u0003q\u0000~\u0000\u000epsq\u0000~\u0000\u0010pps"
+"r\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0015q\u0000~\u0000\u001bt"
+"\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Coll"
+"apse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001eq\u0000~\u0000!sq\u0000~\u0000\"q\u0000~\u0000*q\u0000~\u0000\u001bsr\u0000#com.sun.msv.gr"
+"ammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0018L\u0000\fnamespac"
+"eURIq\u0000~\u0000\u0018xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004ty"
+"pet\u0000)http://www.w3.org/2001/XMLSchema-instancesr\u00000com.sun.ms"
+"v.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000"
+"\r\u0001q\u0000~\u00004sq\u0000~\u0000.t\u0000\u0014mutableTemplateImaget\u00009http://complex.taskmo"
+"del.thorstenberger.de/complexTaskDefq\u0000~\u00004sq\u0000~\u0000\u0007ppsq\u0000~\u0000\tq\u0000~\u0000\u000e"
+"p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0013sq\u0000~\u0000\u0007ppsq\u0000~\u0000%q\u0000~\u0000\u000epq\u0000~\u0000\'q\u0000~\u00000q\u0000~\u00004sq\u0000~\u0000.t\u0000\u0018i"
+"mmutableBackgroundImageq\u0000~\u00008q\u0000~\u00004sq\u0000~\u0000\u0007ppsq\u0000~\u0000\tq\u0000~\u0000\u000ep\u0000sq\u0000~\u0000\u0000"
+"ppq\u0000~\u0000\u0013sq\u0000~\u0000\u0007ppsq\u0000~\u0000%q\u0000~\u0000\u000epq\u0000~\u0000\'q\u0000~\u00000q\u0000~\u00004sq\u0000~\u0000.t\u0000\u0017correctio"
+"nTemplateImageq\u0000~\u00008q\u0000~\u00004sr\u0000\"com.sun.msv.grammar.ExpressionPo"
+"ol\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPo"
+"ol$ClosedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$Close"
+"dHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun"
+"/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000\u000b\u0001pq\u0000~\u0000\u0005q\u0000~\u0000\u000fq\u0000~\u0000;q\u0000~\u0000Bq\u0000~\u0000"
+"\bq\u0000~\u00009q\u0000~\u0000@q\u0000~\u0000\u0006q\u0000~\u0000$q\u0000~\u0000<q\u0000~\u0000Cx"));
            }
            return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
        }

        public class Unmarshaller
            extends de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.AbstractUnmarshallingEventHandlerImpl
        {


            public Unmarshaller(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.UnmarshallingContext context) {
                super(context, "----------");
            }

            protected Unmarshaller(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.UnmarshallingContext context, int startState) {
                this(context);
                state = startState;
            }

            public java.lang.Object owner() {
                return de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl.this;
            }

            public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  9 :
                            revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        case  3 :
                            if (("immutableBackgroundImage" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 4;
                                return ;
                            }
                            state = 6;
                            continue outer;
                        case  6 :
                            if (("correctionTemplateImage" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 7;
                                return ;
                            }
                            state = 9;
                            continue outer;
                        case  0 :
                            if (("mutableTemplateImage" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 1;
                                return ;
                            }
                            state = 3;
                            continue outer;
                    }
                    super.enterElement(___uri, ___local, ___qname, __atts);
                    break;
                }
            }

            public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  9 :
                            revertToParentFromLeaveElement(___uri, ___local, ___qname);
                            return ;
                        case  2 :
                            if (("mutableTemplateImage" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                                context.popAttributes();
                                state = 3;
                                return ;
                            }
                            break;
                        case  8 :
                            if (("correctionTemplateImage" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                                context.popAttributes();
                                state = 9;
                                return ;
                            }
                            break;
                        case  3 :
                            state = 6;
                            continue outer;
                        case  6 :
                            state = 9;
                            continue outer;
                        case  0 :
                            state = 3;
                            continue outer;
                        case  5 :
                            if (("immutableBackgroundImage" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                                context.popAttributes();
                                state = 6;
                                return ;
                            }
                            break;
                    }
                    super.leaveElement(___uri, ___local, ___qname);
                    break;
                }
            }

            public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  9 :
                            revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                            return ;
                        case  3 :
                            state = 6;
                            continue outer;
                        case  6 :
                            state = 9;
                            continue outer;
                        case  0 :
                            state = 3;
                            continue outer;
                    }
                    super.enterAttribute(___uri, ___local, ___qname);
                    break;
                }
            }

            public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  9 :
                            revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                            return ;
                        case  3 :
                            state = 6;
                            continue outer;
                        case  6 :
                            state = 9;
                            continue outer;
                        case  0 :
                            state = 3;
                            continue outer;
                    }
                    super.leaveAttribute(___uri, ___local, ___qname);
                    break;
                }
            }

            public void handleText(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    try {
                        switch (state) {
                            case  9 :
                                revertToParentFromText(value);
                                return ;
                            case  4 :
                                state = 5;
                                eatText1(value);
                                return ;
                            case  3 :
                                state = 6;
                                continue outer;
                            case  6 :
                                state = 9;
                                continue outer;
                            case  0 :
                                state = 3;
                                continue outer;
                            case  7 :
                                state = 8;
                                eatText2(value);
                                return ;
                            case  1 :
                                state = 2;
                                eatText3(value);
                                return ;
                        }
                    } catch (java.lang.RuntimeException e) {
                        handleUnexpectedTextException(value, e);
                    }
                    break;
                }
            }

            private void eatText1(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _ImmutableBackgroundImage = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText2(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _CorrectionTemplateImage = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText3(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _MutableTemplateImage = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

        }

    }

    public static class TextualAnswerTypeImpl implements de.thorstenberger.taskmodel.complex.jaxb.PaintSubTaskDefType.TextualAnswerType, java.io.Serializable, com.sun.xml.bind.JAXBObject, de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.UnmarshallableObject, de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.XMLSerializable, de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.ValidatableObject
    {

        private final static long serialVersionUID = 1L;
        protected boolean has_TextFieldWidth;
        protected int _TextFieldWidth;
        protected boolean has_TextFieldHeight;
        protected int _TextFieldHeight;
        public final static java.lang.Class version = (de.thorstenberger.taskmodel.complex.jaxb.impl.JAXBVersion.class);
        private static com.sun.msv.grammar.Grammar schemaFragment;

        private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
            return (de.thorstenberger.taskmodel.complex.jaxb.PaintSubTaskDefType.TextualAnswerType.class);
        }

        public int getTextFieldWidth() {
            return _TextFieldWidth;
        }

        public void setTextFieldWidth(int value) {
            _TextFieldWidth = value;
            has_TextFieldWidth = true;
        }

        public boolean isSetTextFieldWidth() {
            return has_TextFieldWidth;
        }

        public void unsetTextFieldWidth() {
            has_TextFieldWidth = false;
        }

        public int getTextFieldHeight() {
            return _TextFieldHeight;
        }

        public void setTextFieldHeight(int value) {
            _TextFieldHeight = value;
            has_TextFieldHeight = true;
        }

        public boolean isSetTextFieldHeight() {
            return has_TextFieldHeight;
        }

        public void unsetTextFieldHeight() {
            has_TextFieldHeight = false;
        }

        public de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.UnmarshallingEventHandler createUnmarshaller(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.UnmarshallingContext context) {
            return new de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.TextualAnswerTypeImpl.Unmarshaller(context);
        }

        public void serializeBody(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
            if (has_TextFieldWidth) {
                context.startElement("http://complex.taskmodel.thorstenberger.de/complexTaskDef", "textFieldWidth");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(javax.xml.bind.DatatypeConverter.printInt(((int) _TextFieldWidth)), "TextFieldWidth");
                } catch (java.lang.Exception e) {
                    de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
            if (has_TextFieldHeight) {
                context.startElement("http://complex.taskmodel.thorstenberger.de/complexTaskDef", "textFieldHeight");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(javax.xml.bind.DatatypeConverter.printInt(((int) _TextFieldHeight)), "TextFieldHeight");
                } catch (java.lang.Exception e) {
                    de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
        }

        public void serializeAttributes(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
        }

        public void serializeURIs(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
        }

        public java.lang.Class getPrimaryInterface() {
            return (de.thorstenberger.taskmodel.complex.jaxb.PaintSubTaskDefType.TextualAnswerType.class);
        }

        public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
            if (schemaFragment == null) {
                schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom."
+"sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttr"
+"ibutesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa"
+"\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000p\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002"
+"L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000*com.sun.m"
+"sv.datatype.xsd.MinInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.sun.msv."
+"datatype.xsd.RangeFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\nlimitValuet\u0000\u0012Ljava/lang"
+"/Object;xr\u00009com.sun.msv.datatype.xsd.DataTypeWithValueConstr"
+"aintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.DataTypeWit"
+"hFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needValueCheckFlagL\u0000\bbase"
+"Typet\u0000)Lcom/sun/msv/datatype/xsd/XSDatatypeImpl;L\u0000\fconcreteT"
+"ypet\u0000\'Lcom/sun/msv/datatype/xsd/ConcreteType;L\u0000\tfacetNamet\u0000\u0012"
+"Ljava/lang/String;xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImp"
+"l\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000\u001aL\u0000\btypeNameq\u0000~\u0000\u001aL\u0000\nwhiteSpac"
+"et\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u00009http:"
+"//complex.taskmodel.thorstenberger.de/complexTaskDefpsr\u00005com"
+".sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
+"xp\u0000\u0000sr\u0000 com.sun.msv.datatype.xsd.IntType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000+com.s"
+"un.msv.datatype.xsd.IntegerDerivedType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nbaseFace"
+"tsq\u0000~\u0000\u0018xr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~"
+"\u0000\u001bt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0003intq\u0000~\u0000!sr\u0000*com.sun."
+"msv.datatype.xsd.MaxInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0014ppq\u0000~\u0000!\u0000\u0001"
+"sq\u0000~\u0000\u0013ppq\u0000~\u0000!\u0000\u0000sr\u0000!com.sun.msv.datatype.xsd.LongType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0000xq\u0000~\u0000#q\u0000~\u0000\'t\u0000\u0004longq\u0000~\u0000!sq\u0000~\u0000)ppq\u0000~\u0000!\u0000\u0001sq\u0000~\u0000\u0013ppq\u0000~\u0000!\u0000\u0000sr\u0000$"
+"com.sun.msv.datatype.xsd.IntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000#q\u0000~\u0000\'t\u0000"
+"\u0007integerq\u0000~\u0000!sr\u0000,com.sun.msv.datatype.xsd.FractionDigitsFace"
+"t\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\u0005scalexr\u0000;com.sun.msv.datatype.xsd.DataTypeWit"
+"hLexicalConstraintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xq\u0000~\u0000\u0017ppq\u0000~\u0000!\u0001\u0000sr\u0000#com.sun"
+".msv.datatype.xsd.NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000$q\u0000~\u0000\'t\u0000\u0007decimal"
+"q\u0000~\u0000!q\u0000~\u00008t\u0000\u000efractionDigits\u0000\u0000\u0000\u0000q\u0000~\u00002t\u0000\fminInclusivesr\u0000\u000ejava."
+"lang.Long;\u008b\u00e4\u0090\u00cc\u008f#\u00df\u0002\u0000\u0001J\u0000\u0005valuexr\u0000\u0010java.lang.Number\u0086\u00ac\u0095\u001d\u000b\u0094\u00e0\u008b\u0002\u0000\u0000x"
+"p\u0080\u0000\u0000\u0000\u0000\u0000\u0000\u0000q\u0000~\u00002t\u0000\fmaxInclusivesq\u0000~\u0000<\u007f\u00ff\u00ff\u00ff\u00ff\u00ff\u00ff\u00ffq\u0000~\u0000-q\u0000~\u0000;sr\u0000\u0011jav"
+"a.lang.Integer\u0012\u00e2\u00a0\u00a4\u00f7\u0081\u00878\u0002\u0000\u0001I\u0000\u0005valuexq\u0000~\u0000=\u0080\u0000\u0000\u0000q\u0000~\u0000-q\u0000~\u0000?sq\u0000~\u0000A\u007f"
+"\u00ff\u00ff\u00ffq\u0000~\u0000&q\u0000~\u0000;sq\u0000~\u0000A\u0000\u0000\u0000\u0001sr\u00000com.sun.msv.grammar.Expression$Nu"
+"llSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.Strin"
+"gPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001aL\u0000\fnamespaceURIq\u0000~\u0000\u001axpt\u0000\u000bin"
+"t-derivedq\u0000~\u0000\u001esq\u0000~\u0000\u0006ppsr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\txq\u0000~\u0000\u0003q\u0000~\u0000\rpsq\u0000~\u0000\u000fppsr\u0000"
+"\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000$q\u0000~\u0000\'t\u0000\u0005"
+"QNameq\u0000~\u0000!q\u0000~\u0000Fsq\u0000~\u0000Gq\u0000~\u0000Pq\u0000~\u0000\'sr\u0000#com.sun.msv.grammar.Simpl"
+"eNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001aL\u0000\fnamespaceURIq\u0000~\u0000\u001axr"
+"\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http:/"
+"/www.w3.org/2001/XMLSchema-instancesr\u00000com.sun.msv.grammar.E"
+"xpression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000\f\u0001q\u0000~\u0000Xsq\u0000~"
+"\u0000Rt\u0000\u000etextFieldWidthq\u0000~\u0000\u001eq\u0000~\u0000Xsq\u0000~\u0000\u0006ppsq\u0000~\u0000\bq\u0000~\u0000\rp\u0000sq\u0000~\u0000\u0000ppsq"
+"\u0000~\u0000\u000fppsq\u0000~\u0000\u0013q\u0000~\u0000\u001epq\u0000~\u0000!\u0000\u0000q\u0000~\u0000&q\u0000~\u0000&q\u0000~\u0000;sq\u0000~\u0000A\u0000\u0000\u0000\u0001q\u0000~\u0000Fsq\u0000~\u0000"
+"Gt\u0000\u000bint-derivedq\u0000~\u0000\u001esq\u0000~\u0000\u0006ppsq\u0000~\u0000Kq\u0000~\u0000\rpq\u0000~\u0000Mq\u0000~\u0000Tq\u0000~\u0000Xsq\u0000~\u0000"
+"Rt\u0000\u000ftextFieldHeightq\u0000~\u0000\u001eq\u0000~\u0000Xsr\u0000\"com.sun.msv.grammar.Express"
+"ionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/Express"
+"ionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$"
+"ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lco"
+"m/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000\u0007\u0001pq\u0000~\u0000\u0007q\u0000~\u0000\u0005q\u0000~\u0000\u000eq\u0000~\u0000"
+"Jq\u0000~\u0000dq\u0000~\u0000\\q\u0000~\u0000^x"));
            }
            return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
        }

        public class Unmarshaller
            extends de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.AbstractUnmarshallingEventHandlerImpl
        {


            public Unmarshaller(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.UnmarshallingContext context) {
                super(context, "-------");
            }

            protected Unmarshaller(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.UnmarshallingContext context, int startState) {
                this(context);
                state = startState;
            }

            public java.lang.Object owner() {
                return de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.TextualAnswerTypeImpl.this;
            }

            public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  6 :
                            revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        case  0 :
                            if (("textFieldWidth" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 1;
                                return ;
                            }
                            state = 3;
                            continue outer;
                        case  3 :
                            if (("textFieldHeight" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 4;
                                return ;
                            }
                            state = 6;
                            continue outer;
                    }
                    super.enterElement(___uri, ___local, ___qname, __atts);
                    break;
                }
            }

            public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  2 :
                            if (("textFieldWidth" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                                context.popAttributes();
                                state = 3;
                                return ;
                            }
                            break;
                        case  6 :
                            revertToParentFromLeaveElement(___uri, ___local, ___qname);
                            return ;
                        case  0 :
                            state = 3;
                            continue outer;
                        case  5 :
                            if (("textFieldHeight" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                                context.popAttributes();
                                state = 6;
                                return ;
                            }
                            break;
                        case  3 :
                            state = 6;
                            continue outer;
                    }
                    super.leaveElement(___uri, ___local, ___qname);
                    break;
                }
            }

            public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  6 :
                            revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                            return ;
                        case  0 :
                            state = 3;
                            continue outer;
                        case  3 :
                            state = 6;
                            continue outer;
                    }
                    super.enterAttribute(___uri, ___local, ___qname);
                    break;
                }
            }

            public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  6 :
                            revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                            return ;
                        case  0 :
                            state = 3;
                            continue outer;
                        case  3 :
                            state = 6;
                            continue outer;
                    }
                    super.leaveAttribute(___uri, ___local, ___qname);
                    break;
                }
            }

            public void handleText(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    try {
                        switch (state) {
                            case  6 :
                                revertToParentFromText(value);
                                return ;
                            case  0 :
                                state = 3;
                                continue outer;
                            case  4 :
                                state = 5;
                                eatText1(value);
                                return ;
                            case  3 :
                                state = 6;
                                continue outer;
                            case  1 :
                                state = 2;
                                eatText2(value);
                                return ;
                        }
                    } catch (java.lang.RuntimeException e) {
                        handleUnexpectedTextException(value, e);
                    }
                    break;
                }
            }

            private void eatText1(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _TextFieldHeight = javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                    has_TextFieldHeight = true;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText2(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _TextFieldWidth = javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                    has_TextFieldWidth = true;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

        }

    }

    public class Unmarshaller
        extends de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.UnmarshallingContext context) {
            super(context, "--------------");
        }

        protected Unmarshaller(de.thorstenberger.taskmodel.complex.jaxb.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        if (("textualAnswer" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 5;
                            return ;
                        }
                        state = 7;
                        continue outer;
                    case  13 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  2 :
                        if (("mutableTemplateImage" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                            _Images = ((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl) spawnChildFromEnterElement((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl.class), 3, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("immutableBackgroundImage" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                            _Images = ((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl) spawnChildFromEnterElement((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl.class), 3, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("correctionTemplateImage" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                            _Images = ((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl) spawnChildFromEnterElement((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl.class), 3, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _Images = ((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl) spawnChildFromEnterElement((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl.class), 3, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  7 :
                        if (("colorChangeable" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 8;
                            return ;
                        }
                        state = 10;
                        continue outer;
                    case  0 :
                        attIdx = context.getAttribute("", "id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "inputLanguage");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "interactiveFeedback");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "trash");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("problem" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                            spawnHandlerFromEnterElement((((de.thorstenberger.taskmodel.complex.jaxb.impl.SubTaskDefTypeImpl)de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.this).new Unmarshaller(context)), 1, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                    case  1 :
                        if (("images" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 2;
                            return ;
                        }
                        state = 4;
                        continue outer;
                    case  5 :
                        if (("textFieldWidth" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                            _TextualAnswer = ((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.TextualAnswerTypeImpl) spawnChildFromEnterElement((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.TextualAnswerTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("textFieldHeight" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                            _TextualAnswer = ((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.TextualAnswerTypeImpl) spawnChildFromEnterElement((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.TextualAnswerTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _TextualAnswer = ((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.TextualAnswerTypeImpl) spawnChildFromEnterElement((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.TextualAnswerTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  10 :
                        if (("strokewidthChangeable" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 11;
                            return ;
                        }
                        state = 13;
                        continue outer;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        if (("images" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                            context.popAttributes();
                            state = 4;
                            return ;
                        }
                        break;
                    case  4 :
                        state = 7;
                        continue outer;
                    case  13 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  9 :
                        if (("colorChangeable" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                            context.popAttributes();
                            state = 10;
                            return ;
                        }
                        break;
                    case  6 :
                        if (("textualAnswer" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                            context.popAttributes();
                            state = 7;
                            return ;
                        }
                        break;
                    case  2 :
                        _Images = ((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl) spawnChildFromLeaveElement((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl.class), 3, ___uri, ___local, ___qname));
                        return ;
                    case  7 :
                        state = 10;
                        continue outer;
                    case  0 :
                        attIdx = context.getAttribute("", "id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "inputLanguage");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "interactiveFeedback");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "trash");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  1 :
                        state = 4;
                        continue outer;
                    case  5 :
                        _TextualAnswer = ((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.TextualAnswerTypeImpl) spawnChildFromLeaveElement((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.TextualAnswerTypeImpl.class), 6, ___uri, ___local, ___qname));
                        return ;
                    case  10 :
                        state = 13;
                        continue outer;
                    case  12 :
                        if (("strokewidthChangeable" == ___local)&&("http://complex.taskmodel.thorstenberger.de/complexTaskDef" == ___uri)) {
                            context.popAttributes();
                            state = 13;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        state = 7;
                        continue outer;
                    case  13 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        _Images = ((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl) spawnChildFromEnterAttribute((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl.class), 3, ___uri, ___local, ___qname));
                        return ;
                    case  7 :
                        state = 10;
                        continue outer;
                    case  0 :
                        if (("id" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((de.thorstenberger.taskmodel.complex.jaxb.impl.SubTaskDefTypeImpl)de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.this).new Unmarshaller(context)), 1, ___uri, ___local, ___qname);
                            return ;
                        }
                        if (("inputLanguage" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((de.thorstenberger.taskmodel.complex.jaxb.impl.SubTaskDefTypeImpl)de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.this).new Unmarshaller(context)), 1, ___uri, ___local, ___qname);
                            return ;
                        }
                        if (("interactiveFeedback" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((de.thorstenberger.taskmodel.complex.jaxb.impl.SubTaskDefTypeImpl)de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.this).new Unmarshaller(context)), 1, ___uri, ___local, ___qname);
                            return ;
                        }
                        if (("trash" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((de.thorstenberger.taskmodel.complex.jaxb.impl.SubTaskDefTypeImpl)de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.this).new Unmarshaller(context)), 1, ___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  1 :
                        state = 4;
                        continue outer;
                    case  5 :
                        _TextualAnswer = ((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.TextualAnswerTypeImpl) spawnChildFromEnterAttribute((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.TextualAnswerTypeImpl.class), 6, ___uri, ___local, ___qname));
                        return ;
                    case  10 :
                        state = 13;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        state = 7;
                        continue outer;
                    case  13 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        _Images = ((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl) spawnChildFromLeaveAttribute((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl.class), 3, ___uri, ___local, ___qname));
                        return ;
                    case  7 :
                        state = 10;
                        continue outer;
                    case  0 :
                        attIdx = context.getAttribute("", "id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "inputLanguage");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "interactiveFeedback");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "trash");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  1 :
                        state = 4;
                        continue outer;
                    case  5 :
                        _TextualAnswer = ((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.TextualAnswerTypeImpl) spawnChildFromLeaveAttribute((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.TextualAnswerTypeImpl.class), 6, ___uri, ___local, ___qname));
                        return ;
                    case  10 :
                        state = 13;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  4 :
                            state = 7;
                            continue outer;
                        case  13 :
                            revertToParentFromText(value);
                            return ;
                        case  8 :
                            state = 9;
                            eatText1(value);
                            return ;
                        case  2 :
                            _Images = ((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl) spawnChildFromText((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.ImagesTypeImpl.class), 3, value));
                            return ;
                        case  7 :
                            state = 10;
                            continue outer;
                        case  0 :
                            attIdx = context.getAttribute("", "id");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "inputLanguage");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "interactiveFeedback");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "trash");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            break;
                        case  1 :
                            state = 4;
                            continue outer;
                        case  5 :
                            _TextualAnswer = ((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.TextualAnswerTypeImpl) spawnChildFromText((de.thorstenberger.taskmodel.complex.jaxb.impl.PaintSubTaskDefTypeImpl.TextualAnswerTypeImpl.class), 6, value));
                            return ;
                        case  11 :
                            state = 12;
                            eatText2(value);
                            return ;
                        case  10 :
                            state = 13;
                            continue outer;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _ColorChangeable = javax.xml.bind.DatatypeConverter.parseBoolean(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_ColorChangeable = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _StrokewidthChangeable = javax.xml.bind.DatatypeConverter.parseBoolean(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_StrokewidthChangeable = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
