//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.23 at 01:04:11 CEST 
//


package de.thorstenberger.examServer.dao.xml.jaxb;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/java_files/eclipse/workspace/examServer/jaxb/config.xsd line 5)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RemoteUserManagerURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="studentsLoginEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="loadJVMOnStartup" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ConfigType {


    /**
     * 
     */
    boolean isStudentsLoginEnabled();

    /**
     * 
     */
    void setStudentsLoginEnabled(boolean value);

    boolean isSetStudentsLoginEnabled();

    void unsetStudentsLoginEnabled();

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getTitle();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setTitle(java.lang.String value);

    boolean isSetTitle();

    void unsetTitle();

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getRemoteUserManagerURL();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setRemoteUserManagerURL(java.lang.String value);

    boolean isSetRemoteUserManagerURL();

    void unsetRemoteUserManagerURL();

    /**
     * 
     */
    boolean isLoadJVMOnStartup();

    /**
     * 
     */
    void setLoadJVMOnStartup(boolean value);

    boolean isSetLoadJVMOnStartup();

    void unsetLoadJVMOnStartup();

}
